/*

INSERT INTO User(user_id, name, password, role, notification_number) VALUES
(20, 'Admin', 'admin@123', 'admin', 0),
(21, 'Chef', 'chef@123', 'chef', 0),
(22, 'Shri', 'shri@123', 'employee', 0),
(23, 'Amit', 'amit@123', 'employee', 0),
(24, 'Neha', 'neha@123', 'employee', 0),
(25, 'Raj', 'raj@123', 'employee', 0),
(26, 'Pooja', 'pooja@123', 'employee', 0),
(27, 'Sahil', 'sahil@123', 'employee', 0),
(28, 'Rina', 'rina@123', 'employee', 0),
(29, 'Vikram', 'vikram@123', 'employee', 0),
(30, 'Anjali', 'anjali@123', 'employee', 0),
(31, 'Karan', 'karan@123', 'employee', 0),
(32, 'Priya', 'priya@123', 'employee', 0),
(33, 'Deepak', 'deepak@123', 'employee', 0),
(34, 'Sunita', 'sunita@123', 'employee', 0),
(35, 'Arjun', 'arjun@123', 'employee', 0),
(36, 'Sangeetha', 'sangeetha@123', 'employee', 0),
(37, 'Manish', 'manish@123', 'employee', 0),
(38, 'Meena', 'meena@123', 'employee', 0),
(39, 'Rakesh', 'rakesh@123', 'employee', 0),
(40, 'Kavita', 'kavita@123', 'employee', 0),
(41, 'Naveen', 'naveen@123', 'employee', 0),
(42, 'Sonal', 'sonal@123', 'employee', 0),
(43, 'Rahul', 'rahul@123', 'employee', 0),
(44, 'Sneha', 'sneha@123', 'employee', 0),
(45, 'Anil', 'anil@123', 'employee', 0),
(46, 'Preeti', 'preeti@123', 'employee', 0),
(47, 'Vijay', 'vijay@123', 'employee', 0),
(48, 'Geeta', 'geeta@123', 'employee', 0),
(49, 'Ashok', 'ashok@123', 'employee', 0),
(50, 'Lata', 'lata@123', 'employee', 0),
(51, 'Rohit', 'rohit@123', 'employee', 0),
(52, 'Asha', 'asha@123', 'employee', 0);

INSERT INTO Menu_Item (name, price, description, category, availability, likes, dislikes, recommend_rating, sweet_tooth, diet_id, spice_level_id, cuisine_id) VALUES
('Masala Dosa', 50.00, 'Crispy rice and lentil crepe filled with spicy potato mix', 'breakfast', true, 150, 100, 3.0, false, 1, 2, 2),
('Paneer Butter Masala', 150.00, 'Paneer cubes in rich and creamy tomato gravy', 'lunch', true, 180, 90, 4.2, false, 1, 2, 1),
('Chicken Biryani', 200.00, 'Aromatic basmati rice cooked with tender chicken pieces and spices', 'dinner', true, 170, 130, 3.8, false, 2, 2, 1),
('Gulab Jamun', 40.00, 'Soft and spongy milk-solid-based dessert soaked in sugar syrup', 'all day', true, 190, 110, 4.6, true, 1, 3, 1),
('Idli Sambar', 30.00, 'Steamed rice cakes served with lentil soup and coconut chutney', 'breakfast', true, 120, 140, 2.5, false, 1, 1, 2),
('Hyderabadi Biryani', 250.00, 'Spicy and aromatic biryani with rich flavors', 'lunch', true, 130, 120, 3.3, false, 2, 3, 2),
('Fish Curry', 180.00, 'Spicy and tangy fish curry made with tamarind and spices', 'dinner', true, 110, 150, 2.0, false, 2, 1, 2),
('Rasgulla', 35.00, 'Soft and spongy cottage cheese balls soaked in sugar syrup', 'all day', true, 200, 100, 4.9, true, 1, 3, 1),
('Aloo Paratha', 40.00, 'Whole wheat flatbread stuffed with spiced potato filling', 'breakfast', true, 130, 110, 3.4, false, 1, 2, 1),
('Mutton Rogan Josh', 220.00, 'Tender pieces of mutton cooked in rich and spicy gravy', 'lunch', true, 140, 130, 3.7, false, 2, 2, 1),
('Masala Chai', 20.00, 'Spiced tea made with black tea, milk, and various spices', 'all day', true, 190, 100, 4.8, true, 1, 3, 1),
('Chole Bhature', 60.00, 'Spicy chickpeas served with deep-fried bread', 'breakfast', true, 140, 120, 3.6, false, 1, 2, 1),
('Lamb Vindaloo', 250.00, 'Fiery hot lamb curry with vinegar and spices', 'dinner', true, 160, 150, 3.1, false, 2, 1, 1),
('Jalebi', 30.00, 'Crispy fried sweet dipped in sugar syrup', 'all day', true, 200, 90, 4.7, true, 1, 3, 1),
('Veg Pulao', 100.00, 'Fragrant rice cooked with mixed vegetables and spices', 'lunch', true, 150, 110, 3.9, false, 1, 1, 1),
('Prawn Curry', 220.00, 'Prawns cooked in coconut milk and spices', 'dinner', true, 170, 140, 4.1, false, 2, 2, 2),
('Samosa', 15.00, 'Crispy pastry filled with spiced potatoes and peas', 'all day', true, 180, 110, 4.5, false, 1, 2, 1),
('Egg Curry', 120.00, 'Boiled eggs cooked in a rich and spicy gravy', 'lunch', true, 140, 130, 3.2, false, 3, 1, 1),
('Egg Bhurji', 80.00, 'Spicy scrambled eggs with onions, tomatoes, and spices', 'breakfast', true, 130, 140, 2.9, false, 3, 2, 2),
('Chicken Korma', 210.00, 'Chicken cooked in a creamy and mildly spiced sauce', 'dinner', true, 170, 120, 3.5, false, 2, 2, 2),
('Fish Fry', 160.00, 'Crispy fried fish with a spicy marinade', 'all day', true, 150, 100, 3.0, false, 2, 3, 2),
('Egg Biryani', 180.00, 'Fragrant basmati rice cooked with boiled eggs and spices', 'dinner', true, 160, 130, 3.4, false, 3, 2, 1),
('Butter Chicken', 230.00, 'Chicken in a rich and creamy tomato-based sauce', 'lunch', true, 180, 110, 4.0, false, 2, 2, 1),
('Mutton Biryani', 260.00, 'Fragrant basmati rice cooked with tender mutton pieces and spices', 'dinner', true, 170, 140, 3.8, false, 2, 2, 1),
('Egg Sandwich', 50.00, 'Boiled eggs with mayonnaise and veggies in bread', 'breakfast', true, 140, 130, 3.1, false, 3, 2, 2),
('Fish Biryani', 190.00, 'Aromatic basmati rice cooked with tender fish pieces and spices', 'lunch', true, 160, 110, 3.5, false, 2, 1, 1),
('Shrimp Curry', 230.00, 'Shrimp cooked in a coconut milk and spice gravy', 'dinner', true, 180, 120, 4.3, false, 2, 3, 1),
('Chicken 65', 170.00, 'Spicy deep-fried chicken appetizer', 'all day', true, 190, 110, 4.4, false, 2, 1, 2),
('Crab Masala', 250.00, 'Crab cooked in a spicy masala gravy', 'dinner', true, 170, 140, 4.0, false, 2, 2, 2),
('Egg Fried Rice', 120.00, 'Rice stir-fried with eggs and vegetables', 'lunch', true, 150, 130, 3.2, false, 3, 1, 1),
('Omelette', 60.00, 'Eggs whisked and cooked with onions, tomatoes, and green chilies', 'breakfast', true, 140, 110, 3.3, false, 3, 2, 2),
('Egg Curry with Rice', 140.00, 'Boiled eggs in spicy curry served with steamed rice', 'lunch', true, 160, 120, 3.6, false, 3, 3, 2),
('Fish Tikka', 180.00, 'Marinated fish chunks grilled to perfection', 'dinner', true, 170, 100, 4.2, false, 2, 2, 1),
('Chicken Tikka Masala', 220.00, 'Grilled chicken chunks in a spicy gravy', 'dinner', true, 180, 110, 4.5, false, 2, 1, 1),
('Egg Parantha', 90.00, 'Whole wheat flatbread stuffed with a spicy egg mixture', 'breakfast', true, 150, 120, 4.3, false, 3, 3, 1),
('Egg Roll', 100.00, 'Parantha wrapped around a spicy egg mixture', 'all day', true, 160, 100, 4.6, false, 3, 2, 1),
('Andhra Chicken Curry', 220.00, 'Chicken cooked in a fiery Andhra-style spice blend', 'dinner', true, 170, 130, 4.1, false, 2, 1, 2),
('Chettinad Chicken', 240.00, 'Spicy chicken curry with a rich Chettinad spice mix', 'dinner', true, 190, 110, 4.4, false, 2, 1, 2),
('Spicy Masala Dosa', 60.00, 'Crispy dosa with a spicy potato filling', 'breakfast', true, 130, 70, 3.9, false, 1, 1, 2),
('Karaikudi Mutton', 250.00, 'Mutton cooked with a spicy and tangy Karaikudi masala', 'lunch', true, 180, 80, 4.4, false, 2, 1, 2),
('Spicy Fish Curry', 190.00, 'Fish cooked in a spicy and tangy South Indian curry', 'dinner', true, 160, 90, 3.8, false, 2, 1, 2),
('Coconut Rice', 110.00, 'Fragrant rice cooked with grated coconut and mild spices', 'lunch', true, 140, 70, 4.5, false, 1, 3, 2),
('Curd Rice', 90.00, 'Rice mixed with yogurt and mild spices', 'lunch', true, 130, 80, 4.2, false, 1, 3, 2),
('Vegetable Kichdi', 120.00, 'Comforting rice and lentil dish with vegetables and mild spices', 'lunch', true, 140, 60, 4.1, false, 1, 3, 2),
('Tomato Rice', 100.00, 'Rice cooked with tomatoes and mild spices', 'lunch', true, 120, 70, 4.0, false, 1, 3, 2),
('Mild Sambar', 80.00, 'Mildly spiced lentil soup with vegetables', 'lunch', true, 110, 90, 3.6, false, 1, 3, 2);


INSERT INTO Comment(user_id, item_id, comment) VALUES
(30, 113, 'The Masala Dosa was a delightful breakfast with a perfectly crispy exterior and a flavorful, comforting filling.'),
(35, 114, 'Paneer Butter Masala is simply amazing. The creamy texture and rich flavors are unforgettable.'),
(52, 115, 'Chicken Biryani was good but lacked the robust flavors I was expecting. Overall, it was satisfying.'),
(49, 116, 'Gulab Jamun was divine! Sweet, soft, and soaked in a delicious syrup – truly a blissful bite.'),
(33, 117, 'Idli Sambar was too bland for my taste. The idlis were okay, but the sambar needed more seasoning.'),
(48, 118, 'Hyderabadi Biryani had a wonderful burst of flavor. The spices were well-balanced and aromatic.'),
(31, 119, 'Fish Curry was a bit too tangy and spicy for my liking. The texture was not as expected.'),
(40, 120, 'Rasgulla was heavenly. Soft, spongy, and perfectly sweet – it’s a true delight.'),
(50, 121, 'Aloo Paratha was comforting and well-made. The filling was flavorful, though the paratha could have been crispier.'),
(37, 122, 'Mutton Rogan Josh had an outstanding depth of flavor. The meat was tender and well-seasoned.'),
(38, 123, 'Masala Chai was perfectly spiced and invigorating. A great way to start the day.'),
(41, 124, 'Chole Bhature was superb. The bhature were fluffy, and the chole was rich and full of character.'),
(24, 125, 'Lamb Vindaloo was way too spicy. The heat overpowered the flavors, making it less enjoyable.'),
(26, 126, 'Jalebi was incredibly sweet and crispy. A delightful treat with every bite.'),
(46, 127, 'Veg Pulao was bland and lacking in flavor. It needed more seasoning to be enjoyable.'),
(32, 128, 'Prawn Curry was creamy and delicious. The prawns were tender, and the curry was well-balanced.'),
(43, 129, 'Samosa was crispy and well-seasoned. A perfect snack to enjoy with tea.'),
(25, 130, 'Egg Curry was decent but needed more flavor. The curry was a bit bland and lacked depth.'),
(39, 131, 'Egg Bhurji was a delightful breakfast. The eggs were fluffy and spiced just right.'),
(28, 132, 'Chicken Korma was rich and creamy but a bit too sweet for my taste. It could use a bit more spice.'),
(51, 133, 'Fish Fry was too greasy and lacked the crispy texture I was hoping for.'),
(27, 134, 'Egg Biryani was flavorful and well-cooked. The eggs were perfectly done, and the spices were well-blended.'),
(36, 135, 'Butter Chicken was divine. The creamy sauce and tender chicken made it a memorable meal.'),
(22, 136, 'Mutton Biryani was excellent. The meat was succulent, and the rice was full of flavor.'),
(44, 137, 'Egg Sandwich was basic and lacked seasoning. It was filling but not particularly exciting.'),
(42, 138, 'Fish Biryani was a bit too oily. The flavor was there, but it needed better execution.'),
(34, 139, 'Shrimp Curry was fantastic. The shrimp were juicy, and the curry had a rich and complex flavor.'),
(47, 140, 'Chicken 65 was good but a bit too spicy. The texture was crispy, though.'),
(29, 141, 'Crab Masala was amazing. The crab was tender, and the spices were perfectly balanced.'),
(23, 142, 'Egg Fried Rice was overly dry and lacked flavor. It was not as enjoyable as expected.'),
(45, 143, 'Omelette was fluffy and well-seasoned. A simple but satisfying breakfast option.'),
(30, 144, 'Egg Curry with Rice was comforting. The flavors were well-balanced, and the rice was cooked perfectly.'),
(35, 145, 'Fish Tikka was too dry and lacked flavor. The texture was not what I expected.'),
(52, 146, 'Chicken Tikka Masala was top-notch. The chicken was tender, and the sauce was rich and flavorful.'),
(49, 147, 'Egg Parantha was enjoyable. The filling was tasty, but the paratha could have been softer.'),
(33, 148, 'Egg Roll was tasty but a bit greasy. The flavors were good, though.'),
(48, 149, 'Andhra Chicken Curry was superbly spicy. The heat was intense but enjoyable if you like it hot.'),
(31, 150, 'Chettinad Chicken was flavorful but overly spicy. The dish was well-cooked but too hot for my taste.'),
(40, 151, 'Spicy Masala Dosa was delicious. The dosa was crispy, and the filling was perfectly spiced.'),
(50, 152, 'Karaikudi Mutton was good but needed more seasoning. The flavors were not as vibrant as expected.'),
(37, 153, 'Spicy Fish Curry was too spicy and overwhelming. The flavor was lost due to the excessive heat.'),
(38, 154, 'Coconut Rice was delightful. The coconut added a wonderful touch to the rice.'),
(41, 155, 'Curd Rice was a bit too sour for my taste. The rice was well-cooked, though.'),
(24, 156, 'Vegetable Kichdi was wholesome and comforting. It was a perfect blend of flavors and textures.'),
(26, 157, 'Tomato Rice was too bland. It needed more seasoning and a bit of zest.'),
(46, 158, 'Mild Sambar was quite bland. It needed more spices to enhance the flavor.'),
(32, 113, 'The Masala Dosa was crispy and delicious, though I felt it could have used a bit more spice.'),
(43, 114, 'Paneer Butter Masala was exceptional. The creamy gravy and tender paneer made for an indulgent meal.'),
(25, 115, 'Chicken Biryani was decent but a bit too oily. The flavor was good, but it missed the perfect balance.'),
(39, 116, 'Gulab Jamun was a real treat. Sweet and spongy with just the right amount of syrup.'),
(28, 117, 'Idli Sambar was quite bland. The idlis were soft, but the sambar lacked the typical zest.'),
(51, 118, 'Hyderabadi Biryani was flavorful and aromatic, but a tad too spicy for my preference.'),
(27, 119, 'Fish Curry was rich and flavorful, though it was a bit too tangy. The spice level was just right.'),
(36, 120, 'Rasgulla was a sweet delight. Soft and delicious, it was the highlight of the meal.'),
(22, 121, 'Aloo Paratha was comforting but slightly under-seasoned. The texture was good, though.'),
(44, 122, 'Mutton Rogan Josh was flavorful and tender, though a bit too oily for my liking.'),
(42, 123, 'Masala Chai was refreshing with the right balance of spices. A perfect way to start the day.'),
(34, 124, 'Chole Bhature was fantastic. The bhature were fluffy, and the chole had a rich and savory taste.'),
(47, 125, 'Lamb Vindaloo was extremely spicy and overpowering. The flavors were good, but the heat was too much.'),
(29, 126, 'Jalebi was crisp and sweet. A delicious dessert that was enjoyable with every bite.'),
(23, 127, 'Veg Pulao was a bit underwhelming. The flavors were mild, and it needed more seasoning.'),
(45, 128, 'Prawn Curry was flavorful and well-cooked. The prawns were juicy, and the sauce was delightful.'),
(30, 129, 'Samosa was crisp and well-seasoned. A perfect snack with a nice balance of spices.'),
(35, 130, 'Egg Curry was flavorful but slightly bland. It could use a bit more seasoning for an enhanced taste.'),
(52, 131, 'Egg Bhurji was nicely spiced and cooked to perfection. It was a delightful breakfast option.'),
(49, 132, 'Chicken Korma was rich and creamy but slightly too sweet. The balance of flavors could be improved.'),
(33, 133, 'Fish Fry was crispy but a bit greasy. The flavor was decent, but the texture could be better.'),
(48, 134, 'Egg Biryani was flavorful and well-seasoned. The rice and eggs were cooked perfectly.'),
(31, 135, 'Butter Chicken was creamy and delicious. The flavors were well-balanced, making it a delightful dish.'),
(40, 136, 'Mutton Biryani was flavorful but lacked the expected level of spice. Overall, it was satisfying.'),
(50, 137, 'Egg Sandwich was basic and somewhat bland. It was okay but lacked excitement.'),
(37, 138, 'Fish Biryani was flavorful but a bit oily. The fish was well-cooked, but the rice could be less greasy.'),
(38, 139, 'Shrimp Curry was rich and flavorful. The shrimp were well-cooked, and the sauce was delightful.'),
(41, 140, 'Chicken 65 was crispy but overly spicy. The flavor was good, but it could use less heat.'),
(24, 141, 'Crab Masala was a real treat. The crab was tender, and the masala was rich and aromatic.'),
(26, 142, 'Egg Fried Rice was dry and lacked flavor. It needed more seasoning and a bit of moisture.'),
(46, 143, 'Omelette was fluffy and well-seasoned. A simple and satisfying breakfast choice.'),
(32, 144, 'Egg Curry with Rice was comforting. The curry was flavorful, and the rice was cooked well.'),
(43, 145, 'Fish Tikka was dry and lacked flavor. The texture was not ideal, and the taste was underwhelming.'),
(25, 146, 'Chicken Tikka Masala was top-notch. The chicken was tender, and the sauce was rich and flavorful.'),
(39, 147, 'Egg Parantha was tasty but slightly overcooked. The filling was good, but the paratha needed more softness.'),
(28, 148, 'Egg Roll was enjoyable but a bit greasy. The flavors were good, though.'),
(51, 149, 'Andhra Chicken Curry was superbly spicy. If you enjoy heat, this dish is a must-try!'),
(27, 150, 'Chettinad Chicken was flavorful but overly spicy. The dish was well-cooked but too hot for my taste.'),
(36, 151, 'Spicy Masala Dosa was crispy and flavorful. The filling had a great balance of spices.'),
(22, 152, 'Karaikudi Mutton was good but needed more seasoning. The flavors were nice but not as vibrant as expected.'),
(44, 153, 'Spicy Fish Curry was overly spicy. The heat was overwhelming and masked the other flavors.'),
(42, 154, 'Coconut Rice was delightful. The coconut flavor added a unique touch to the rice.'),
(34, 155, 'Curd Rice was a bit sour. It was well-prepared, but the taste was not to my liking.'),
(47, 156, 'Vegetable Kichdi was comforting and well-balanced. A hearty dish with great flavors.'),
(29, 157, 'Tomato Rice was bland and needed more seasoning. The dish lacked the expected tangy flavor.'),
(23, 158, 'Mild Sambar was too bland. It needed more spices to enhance the flavor.'),
(45, 113, 'The Masala Dosa had a great crunch, but it was missing a bit of the traditional spice kick.'),
(30, 114, 'Paneer Butter Masala was fantastic! The paneer was soft, and the gravy was perfectly spiced.'),
(35, 115, 'Chicken Biryani was okay. The rice was flavorful, but the chicken was a bit dry.'),
(52, 116, 'Gulab Jamun was sweet and satisfying, though it could have been a bit warmer.'),
(49, 117, 'Idli Sambar was decent. The idlis were soft, but the sambar lacked depth and seasoning.'),
(33, 118, 'Hyderabadi Biryani had a nice aroma but was overly spicy for my taste.'),
(48, 119, 'Fish Curry was rich and flavorful, but the fish was a bit overcooked.'),
(31, 120, 'Rasgulla was delightful! Soft and sweet, it was the perfect end to the meal.'),
(40, 121, 'Aloo Paratha was good, but the potato filling needed more seasoning.'),
(50, 122, 'Mutton Rogan Josh was flavorful but too greasy. The meat was tender, though.'),
(37, 123, 'Masala Chai was well-spiced and soothing, a perfect beverage for a cold day.'),
(38, 124, 'Chole Bhature was excellent. The chole was spicy and flavorful, and the bhature were light and fluffy.'),
(41, 125, 'Lamb Vindaloo was too spicy. The heat overshadowed the flavors, making it hard to enjoy.'),
(24, 126, 'Jalebi was crispy and perfectly sweet. A classic dessert done right.'),
(26, 127, 'Veg Pulao was a bit bland and lacked the vibrant flavors I was expecting.'),
(46, 128, 'Prawn Curry was delicious with a rich, flavorful sauce. The prawns were cooked just right.'),
(32, 129, 'Samosa was crispy and had a nice filling, though it could use a bit more spice.'),
(43, 130, 'Egg Curry was tasty but the gravy could be thicker. Overall, a satisfying dish.'),
(25, 131, 'Egg Bhurji was perfectly spiced and had a great texture. A great start to the day.'),
(39, 132, 'Chicken Korma was creamy and comforting, though it could use a bit more spice.'),
(28, 133, 'Fish Fry was crunchy and well-seasoned. A bit greasy but still enjoyable.'),
(51, 134, 'Egg Biryani was flavorful with a good mix of spices. The eggs were a nice touch.'),
(27, 135, 'Butter Chicken was fantastic with a creamy sauce and tender chicken pieces. Highly recommended.'),
(36, 136, 'Mutton Biryani was good but a bit heavy. The flavors were rich but a little too strong.'),
(22, 137, 'Egg Sandwich was simple and lacked flavor. It was okay but not memorable.'),
(44, 138, 'Fish Biryani was flavorful with tender fish, though it was a bit greasy.'),
(42, 139, 'Shrimp Curry was rich and satisfying. The shrimp were cooked well, and the sauce was excellent.'),
(34, 140, 'Chicken 65 was crispy but a bit too spicy. The flavor was good, but the heat was overwhelming.'),
(47, 141, 'Crab Masala was flavorful with tender crab. A bit messy but worth it for the taste.'),
(29, 142, 'Egg Fried Rice was a bit bland and dry. It needed more seasoning and moisture.'),
(23, 143, 'Omelette was fluffy and well-seasoned. A great addition to my breakfast.'),
(45, 144, 'Egg Curry with Rice was comforting and well-balanced. The combination worked perfectly.'),
(30, 145, 'Fish Tikka was decent but lacked flavor. It was a bit dry and could use more seasoning.'),
(35, 146, 'Chicken Tikka Masala was delicious with a rich sauce. The chicken was perfectly cooked.'),
(52, 147, 'Egg Parantha was flavorful but a bit overcooked. The egg filling was good, but the paratha needed to be softer.'),
(49, 148, 'Egg Roll was good but a bit greasy. The flavor was enjoyable, though.'),
(33, 149, 'Andhra Chicken Curry was wonderfully spicy. A great dish for spice lovers.'),
(48, 150, 'Chettinad Chicken was flavorful but extremely spicy. The heat was a bit much for me.'),
(31, 151, 'Spicy Masala Dosa was crisp and well-seasoned. The filling had a great balance of spices.'),
(40, 152, 'Karaikudi Mutton was flavorful but a bit too fatty. The taste was rich, but the texture could be improved.'),
(50, 153, 'Spicy Fish Curry was extremely spicy. The flavor was good but the heat was overpowering.'),
(37, 154, 'Coconut Rice was fragrant and delicious. The coconut added a nice touch.'),
(38, 155, 'Curd Rice was a bit sour and needed more seasoning. It was okay but not great.'),
(41, 156, 'Vegetable Kichdi was comforting and well-cooked. The flavors were balanced and satisfying.'),
(24, 157, 'Tomato Rice was too bland. It needed more seasoning and the tomatoes could be more prominent.'),
(26, 158, 'Mild Sambar was too mild for my taste. It lacked the spices I was expecting.'),
(46, 113, 'The Masala Dosa was crispy and had a perfect balance of spices. Loved it!'),
(32, 114, 'Paneer Butter Masala was rich and creamy, with perfectly cooked paneer.'),
(43, 115, 'Chicken Biryani had a wonderful aroma, but the chicken could have been more tender.'),
(25, 116, 'Gulab Jamun was a bit too sweet for my taste, but the texture was perfect.'),
(39, 117, 'Idli Sambar was nice, but the sambar could use a bit more spice and flavor.'),
(28, 118, 'Hyderabadi Biryani was flavorful, though a bit on the spicy side.'),
(51, 119, 'Fish Curry had a great balance of flavors, though the fish was slightly overcooked.'),
(27, 120, 'Rasgulla was soft and spongy, with just the right amount of sweetness.'),
(36, 121, 'Aloo Paratha was decent, but the potato filling needed a bit more seasoning.'),
(22, 122, 'Mutton Rogan Josh was hearty and flavorful, but a bit too oily for my liking.'),
(44, 123, 'Masala Chai was perfectly spiced. A great pick-me-up for the afternoon.'),
(42, 124, 'Chole Bhature was delicious, with spicy chole and perfectly puffed bhature.'),
(34, 125, 'Lamb Vindaloo was very spicy. The heat was overpowering but the flavors were good.'),
(47, 126, 'Jalebi was crispy and sweet. A great dessert to end the meal.'),
(29, 127, 'Veg Pulao was good but could use a bit more seasoning to enhance the flavors.'),
(23, 128, 'Prawn Curry had a rich sauce and well-cooked prawns, though a bit more spice would be welcome.'),
(45, 129, 'Samosa was crispy and flavorful, though the filling was slightly under-seasoned.'),
(30, 130, 'Egg Curry was hearty and comforting. The gravy was flavorful and satisfying.'),
(35, 131, 'Egg Bhurji was well-spiced and fluffy. A great breakfast option.'),
(52, 132, 'Chicken Korma was creamy and delicious, though a bit too mild in spice.'),
(49, 133, 'Fish Fry was crispy and flavorful, but a bit greasy.'),
(33, 134, 'Egg Biryani was flavorful with a good mix of spices. The eggs were a nice addition.'),
(48, 135, 'Butter Chicken was rich and creamy, with tender chicken pieces. Loved it!'),
(31, 136, 'Mutton Biryani was flavorful but a bit heavy. The rice and meat were well-cooked.'),
(40, 137, 'Egg Sandwich was simple but lacked flavor. It was a bit bland.'),
(50, 138, 'Fish Biryani had a good mix of flavors, though the fish was slightly overcooked.'),
(37, 139, 'Shrimp Curry was flavorful with a creamy sauce. The shrimp were well-cooked.'),
(38, 140, 'Chicken 65 was crispy but overly spicy. The flavor was good but the heat was too much.'),
(41, 141, 'Crab Masala was flavorful and spicy. The crab was well-cooked and tender.'),
(24, 142, 'Egg Fried Rice was a bit dry. The flavors were okay, but it needed more moisture.'),
(26, 143, 'Omelette was well-seasoned and fluffy. A solid breakfast choice.'),
(46, 144, 'Egg Curry with Rice was comforting and flavorful. The combination worked well.'),
(32, 145, 'Fish Tikka was decent but lacked flavor. The texture was a bit dry.'),
(43, 146, 'Chicken Tikka Masala was rich and flavorful. The chicken was perfectly cooked.'),
(25, 147, 'Egg Parantha was good but a bit overcooked. The filling was flavorful.'),
(39, 148, 'Egg Roll was tasty but a bit greasy. The flavor was enjoyable.'),
(28, 149, 'Andhra Chicken Curry was spicy and full of flavor. Perfect for spice lovers.'),
(51, 150, 'Chettinad Chicken was spicy and flavorful. The heat was intense but enjoyable.'),
(27, 151, 'Spicy Masala Dosa was crispy and flavorful. The filling had a good spice level.'),
(36, 152, 'Karaikudi Mutton was flavorful but too fatty. The taste was rich but the texture could be improved.'),
(22, 153, 'Spicy Fish Curry was very spicy. The flavor was good but the heat was overwhelming.'),
(44, 154, 'Coconut Rice was aromatic and flavorful. The coconut added a nice touch.'),
(42, 155, 'Curd Rice was a bit bland and needed more seasoning. It was okay but not memorable.'),
(34, 156, 'Vegetable Kichdi was comforting and well-balanced. The flavors were satisfying.'),
(47, 157, 'Tomato Rice was bland and needed more seasoning. The tomatoes could be more prominent.'),
(29, 158, 'Mild Sambar was too mild for my taste. It lacked the spices I was expecting.');


INSERT INTO Menu_Item_Sentiment(item_id, sentiment, type) VALUES
(113, 'comforting', 'positive'),
(113, 'crispy', 'positive'),
(113, 'delicious', 'positive'),
(113, 'delightful', 'positive'),
(113, 'flavorful', 'positive'),
(113, 'great', 'positive'),
(113, 'light', 'positive'),
(114, 'amazing', 'positive'),
(114, 'creamy', 'positive'),
(114, 'exceptional', 'positive'),
(114, 'fantastic', 'positive'),
(114, 'indulgent', 'positive'),
(114, 'perfectly cooked', 'positive'),
(114, 'rich', 'positive'),
(114, 'tender', 'positive'),
(115, 'dry', 'negative'),
(115, 'flavorful', 'positive'),
(115, 'good', 'positive'),
(115, 'oily', 'negative'),
(115, 'robust', 'positive'),
(115, 'satisfying', 'positive'),
(115, 'tender', 'positive'),
(115, 'wonderful', 'positive'),
(116, 'blissful bite', 'positive'),
(116, 'delicious', 'positive'),
(116, 'divine', 'positive'),
(116, 'satisfying', 'positive'),
(116, 'sweet', 'positive'),
(116, 'too sweet', 'negative'),
(116, 'treat', 'positive'),
(117, 'bland', 'negative'),
(118, 'aromatic', 'positive'),
(118, 'balanced', 'positive'),
(118, 'burst of flavor', 'positive'),
(118, 'flavorful', 'positive'),
(118, 'spicy', 'positive'),
(118, 'too spicy', 'negative'),
(118, 'well-balanced', 'positive'),
(118, 'wonderful', 'positive'),
(119, 'flavorful', 'positive'),
(119, 'great', 'positive'),
(119, 'light', 'positive'),
(119, 'overcooked', 'negative'),
(119, 'rich', 'positive'),
(119, 'spicy', 'positive'),
(120, 'delicious', 'positive'),
(120, 'delightful', 'positive'),
(120, 'heavenly', 'positive'),
(120, 'light', 'positive'),
(120, 'sweet', 'positive'),
(120, 'true delight', 'positive'),
(121, 'comforting', 'positive'),
(121, 'flavorful', 'positive'),
(121, 'good', 'positive'),
(121, 'light', 'positive'),
(122, 'flavorful', 'positive'),
(122, 'greasy', 'negative'),
(122, 'oily', 'negative'),
(122, 'outstanding', 'positive'),
(122, 'tender', 'positive'),
(122, 'well-seasoned', 'positive'),
(123, 'fresh', 'positive'),
(123, 'great', 'positive'),
(123, 'invigorating', 'positive'),
(123, 'refreshing', 'positive'),
(124, 'delicious', 'positive'),
(124, 'excellent', 'positive'),
(124, 'fantastic', 'positive'),
(124, 'flavorful', 'positive'),
(124, 'fluffy', 'positive'),
(124, 'full of character', 'positive'),
(124, 'light', 'positive'),
(124, 'rich', 'positive'),
(124, 'savory', 'positive'),
(124, 'spicy', 'positive'),
(124, 'superb', 'positive'),
(125, 'good', 'positive'),
(125, 'hard', 'negative'),
(125, 'overpowering', 'negative'),
(125, 'spicy', 'positive'),
(125, 'too spicy', 'negative'),
(126, 'crispy', 'positive'),
(126, 'delicious', 'positive'),
(126, 'delightful', 'positive'),
(126, 'great', 'positive'),
(126, 'light', 'positive'),
(126, 'sweet', 'positive'),
(126, 'treat', 'positive'),
(127, 'bland', 'negative'),
(127, 'good', 'positive'),
(127, 'underwhelming', 'negative'),
(127, 'vibrant flavors', 'positive'),
(127, 'vibrant', 'positive'),
(128, 'balanced', 'positive'),
(128, 'creamy', 'positive'),
(128, 'delicious', 'positive'),
(128, 'delightful', 'positive'),
(128, 'flavorful', 'positive'),
(128, 'juicy', 'positive'),
(128, 'light', 'positive'),
(128, 'rich', 'positive'),
(128, 'tender', 'positive'),
(128, 'well-balanced', 'positive'),
(129, 'crispy', 'positive'),
(129, 'flavorful', 'positive'),
(129, 'light', 'positive'),
(129, 'well-seasoned', 'positive'),
(130, 'bland', 'negative'),
(130, 'comforting', 'positive'),
(130, 'flavorful', 'positive'),
(130, 'light', 'positive'),
(130, 'satisfying', 'positive'),
(130, 'tasty', 'positive'),
(131, 'delightful', 'positive'),
(131, 'fluffy', 'positive'),
(131, 'great', 'positive'),
(131, 'light', 'positive'),
(132, 'comforting', 'positive'),
(132, 'creamy', 'positive'),
(132, 'delicious', 'positive'),
(132, 'light', 'positive'),
(132, 'rich', 'positive'),
(132, 'sweet', 'positive'),
(132, 'too sweet', 'negative'),
(133, 'crispy', 'positive'),
(133, 'flavorful', 'positive'),
(133, 'greasy', 'negative'),
(133, 'well-seasoned', 'positive'),
(134, 'flavorful', 'positive'),
(134, 'good', 'positive'),
(134, 'well-seasoned', 'positive'),
(135, 'balanced', 'positive'),
(135, 'creamy', 'positive'),
(135, 'delicious', 'positive'),
(135, 'delightful', 'positive'),
(135, 'divine', 'positive'),
(135, 'fantastic', 'positive'),
(135, 'light', 'positive'),
(135, 'memorable', 'positive'),
(135, 'rich', 'positive'),
(135, 'tender', 'positive'),
(135, 'well-balanced', 'positive'),
(136, 'excellent', 'positive'),
(136, 'flavorful', 'positive'),
(136, 'full of flavor', 'positive'),
(136, 'good', 'positive'),
(136, 'rich', 'positive'),
(136, 'satisfying', 'positive'),
(136, 'succulent', 'positive'),
(137, 'bland', 'negative'),
(137, 'memorable', 'positive'),
(138, 'flavorful', 'positive'),
(138, 'good', 'positive'),
(138, 'greasy', 'negative'),
(138, 'light', 'positive'),
(138, 'oily', 'negative'),
(138, 'overcooked', 'negative'),
(138, 'tender', 'positive'),
(139, 'creamy', 'positive'),
(139, 'delightful', 'positive'),
(139, 'excellent', 'positive'),
(139, 'fantastic', 'positive'),
(139, 'flavorful', 'positive'),
(139, 'juicy', 'positive'),
(139, 'light', 'positive'),
(139, 'rich', 'positive'),
(139, 'satisfying', 'positive'),
(140, 'crispy', 'positive'),
(140, 'good', 'positive'),
(140, 'overwhelming', 'negative'),
(140, 'spicy', 'positive'),
(140, 'too spicy', 'negative'),
(141, 'amazing', 'positive'),
(141, 'aromatic', 'positive'),
(141, 'balanced', 'positive'),
(141, 'flavorful', 'positive'),
(141, 'perfectly balanced', 'positive'),
(141, 'rich', 'positive'),
(141, 'spicy', 'positive'),
(141, 'tender', 'positive'),
(141, 'treat', 'positive'),
(142, 'bland and dry', 'negative'),
(142, 'bland', 'negative'),
(142, 'dry', 'negative'),
(143, 'fluffy', 'positive'),
(143, 'great', 'positive'),
(143, 'satisfying', 'positive'),
(143, 'well-seasoned', 'positive'),
(144, 'balanced', 'positive'),
(144, 'comforting', 'positive'),
(144, 'flavorful', 'positive'),
(144, 'well-balanced', 'positive'),
(145, 'dry', 'negative'),
(145, 'too dry', 'negative'),
(145, 'underwhelming', 'negative'),
(146, 'delicious', 'positive'),
(146, 'flavorful', 'positive'),
(146, 'perfectly cooked', 'positive'),
(146, 'rich', 'positive'),
(146, 'tender', 'positive'),
(146, 'top-notch', 'positive'),
(147, 'flavorful', 'positive'),
(147, 'good', 'positive'),
(147, 'light', 'positive'),
(147, 'overcooked', 'negative'),
(147, 'tasty', 'positive'),
(148, 'good', 'positive'),
(148, 'greasy', 'negative'),
(148, 'tasty', 'positive'),
(149, 'full of flavor', 'positive'),
(149, 'great', 'positive'),
(149, 'spicy', 'positive'),
(149, 'superb', 'positive'),
(149, 'wonderful', 'positive'),
(150, 'flavorful', 'positive'),
(150, 'spicy', 'positive'),
(150, 'too hot', 'negative'),
(151, 'crispy', 'positive'),
(151, 'delicious', 'positive'),
(151, 'flavorful', 'positive'),
(151, 'good', 'positive'),
(151, 'great', 'positive'),
(151, 'spicy', 'positive'),
(151, 'well-seasoned', 'positive'),
(152, 'flavorful', 'positive'),
(152, 'good', 'positive'),
(152, 'rich', 'positive'),
(152, 'too fatty', 'negative'),
(152, 'vibrant', 'positive'),
(153, 'good', 'positive'),
(153, 'overpowering', 'negative'),
(153, 'overwhelming', 'negative'),
(153, 'spicy', 'positive'),
(153, 'too spicy', 'negative'),
(154, 'aromatic', 'positive'),
(154, 'delicious', 'positive'),
(154, 'delightful', 'positive'),
(154, 'flavorful', 'positive'),
(154, 'light', 'positive'),
(154, 'unique', 'positive'),
(154, 'wonderful', 'positive'),
(155, 'bland', 'negative'),
(155, 'great', 'positive'),
(155, 'memorable', 'positive'),
(155, 'sour', 'negative'),
(156, 'balanced', 'positive'),
(156, 'comforting', 'positive'),
(156, 'great', 'positive'),
(156, 'perfect blend', 'positive'),
(156, 'satisfying', 'positive'),
(156, 'well-balanced', 'positive'),
(156, 'wholesome', 'positive'),
(157, 'bland', 'negative'),
(158, 'bland', 'negative');

*/
